//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourPlanner.Models.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPackage
    {
        public int PackageID { get; set; }
        public string PackageImage { get; set; }
        public string Packagename { get; set; }
        public string PackageDescription { get; set; }
    }
}
